import {
  Grid,
  Hero,
  Layout,
  Marquee,
  ProductCard,
  ProductList,
} from "@components";
import { InferGetStaticPropsType, NextPage } from "next";
import { FunctionComponent } from "react";
import { getShopifyAPIConfig } from "../framework/shopify/api";
import { getAllProductsAPI } from "../framework/shopify/api/product";

export const getStaticProps = async () => {
  const config = getShopifyAPIConfig();
  const products = await getAllProductsAPI(config);

  return {
    props: {
      products,
    },
    revalidate: 4 * 60 * 60,
  };
};

type HomePage<T> = NextPage<T> & {
  Layout: FunctionComponent;
};

type HomePageProps = InferGetStaticPropsType<typeof getStaticProps>;

const Home: HomePage<HomePageProps> = ({ products }: HomePageProps) => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    <>
      <Grid>
        <ProductList products={products} />
      </Grid>
      <Hero
        headline="Cookies, ice cream and muffin"
        description="Marshmallow tart jelly icing cotton candy tootsie roll cotton candy candy canes. Cake liquorice sesame snaps. Cupcake cake cheesecake pie marshmallow lollipop soufflé marshmallow dessert. Cheesecake jujubes halvah chupa chups lollipop tootsie roll. Jelly-o tiramisu jelly toffee cake croissant lemon drops pudding. Donut sesame snaps gummi bears toffee. Sesame snaps jelly-o oat cake chocolate marzipan cake lollipop. Gingerbread cheesecake jujubes fruitcake cake. Tiramisu cotton candy marzipan candy canes oat cake pudding bonbon."
      />
      <Marquee gradient={false}>
        {products.slice(0, 3).map((product) => (
          <ProductCard key={product.id} variant="slim" product={product} />
        ))}
      </Marquee>
      <Grid layout="B">
        <ProductList products={products} />
      </Grid>
      <Marquee gradient={false} variant="secondary">
        {products.slice(0, 3).map((product) => (
          <ProductCard key={product.id} variant="slim" product={product} />
        ))}
      </Marquee>
    </>
    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  );
};

Home.Layout = Layout;

export default Home;
